name: Build All Containers
run-name: Build all container images in repository using dev branch
on: [push]

jobs:
  build-colmap:
    uses: ./.github/workflows/package-containers.yml
    with:
      build_dir: ./colmap/
  build-hloc:
    uses: ./.github/workflows/package-containers.yml
    needs: build-colmap
    with:
      build_dir: ./hloc/
  build-pixsfm:
    uses: ./.github/workflows/package-containers.yml
    needs: build-hloc
    with:
      build_dir: ./pixel-perfect-sfm/

