name: Package Containers
run-name: Building & Publish Containers

on:
  workflow_call:
    inputs:
      build_dir:
        required: true
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.7.0

      - name: Log in to Github Packages
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get org name
        id: org-name
        run: echo ${{ github.repository }} | awk -F / '{ print "ORGNAME=" $1 }' >> $GITHUB_OUTPUT

      - name: Get image name
        id: img-name
        uses: mikefarah/yq@master
        with:
          cmd: yq '.tag' '${{ inputs.build_dir }}/info.yml'

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.org-name.outputs.ORGNAME }}/${{ steps.img-name.outputs.result }}
